# This is the main build configuration for your Netlify site.
[build]
  base = "artisan-direct"
  command = "npm run build"
  publish = "artisan-direct/build"

  # This section tells the build server how to behave.
  [build.environment]
    # **THE FIX**: This tells Node.js to use less memory, preventing crashes on Netlify's free tier.
    NODE_OPTIONS = "--max-old-space-size=4096"

# This section tells Netlify's security scanner to ignore public keys.
[build.processing.secrets]
  omit_keys = [
    "REACT_APP_FIREBASE_API_KEY",
    "REACT_APP_FIREBASE_AUTH_DOMAIN",
    "REACT_APP_FIREBASE_PROJECT_ID",
    "REACT_APP_FIREBASE_STORAGE_BUCKET",
    "REACT_APP_FIREBASE_MESSAGING_SENDER_ID",
    "REACT_APP_FIREBASE_APP_ID",
    "REACT_APP_FIREBASE_MEASUREMENT_ID",
    "REACT_APP_API_URL"
  ]