[build]
  # This tells Netlify's secrets scanner to ignore these specific keys.
  # They are safe to be in the frontend build output as required by Firebase.
  [build.environment]
    SECRETS_SCAN_OMIT_KEYS = [
      "REACT_APP_FIREBASE_API_KEY",
      "REACT_APP_FIREBASE_AUTH_DOMAIN",
      "REACT_APP_FIREBASE_PROJECT_ID",
      "REACT_APP_FIREBASE_STORAGE_BUCKET",
      "REACT_APP_FIREBASE_MESSAGING_SENDER_ID",
      "REACT_APP_FIREBASE_APP_ID",
      "REACT_APP_FIREBASE_MEASUREMENT_ID",
      "REACT_APP_API_URL"
    ]