# This is the main build configuration for your Netlify site.
[build]
  # The root of your frontend application
  base = "artisan-direct"
  
  # The command to build your site, with the memory fix included
  command = "NODE_OPTIONS=--max-old-space-size=4096 npm run build"
  
  # The directory that contains the final, built site (relative to the base)
  publish = "build"

# This section tells Netlify's security scanner to ignore public keys.
[build.processing.secrets]
  omit_keys = [
    "REACT_APP_FIREBASE_API_KEY",
    "REACT_APP_FIREBASE_AUTH_DOMAIN",
    "REACT_APP_FIREBASE_PROJECT_ID",
    "REACT_APP_FIREBASE_STORAGE_BUCKET",
    "REACT_APP_FIREBASE_MESSAGING_SENDER_ID",
    "REACT_APP_FIREBASE_APP_ID",
    "REACT_APP_FIREBASE_MEASUREMENT_ID",
    "REACT_APP_API_URL"
  ]