# This is the final, correct build configuration for your Netlify site.
[build]
  # The root of your frontend application
  base = "artisan-direct"
  
  # **THE FIX**: "CI=false" tells React not to treat warnings as errors.
  # This will allow your successful build to complete without failing.
  command = "CI=false npm run build"
  
  # The directory that contains the final, built site
  publish = "build"

# This section tells Netlify's security scanner to ignore public keys.
[build.processing.secrets]
  omit_keys = [
    "REACT_APP_FIREBASE_API_KEY",
    "REACT_APP_FIREBASE_AUTH_DOMAIN",
    "REACT_APP_FIREBASE_PROJECT_ID",
    "REACT_APP_FIREBASE_STORAGE_BUCKET",
    "REACT_APP_FIREBASE_MESSAGING_SENDER_ID",
    "REACT_APP_FIREBASE_APP_ID",
    "REACT_APP_FIREBASE_MEASUREMENT_ID",
    "REACT_APP_API_URL"
  ]